// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjVjlcUKYUBb62x4K8WUGI47mXXlfKTtI',
    appId: '1:748007732162:web:ff42373829ce3137785c5b',
    messagingSenderId: '748007732162',
    projectId: 'actingweb-firstapp',
    authDomain: 'actingweb-firstapp.firebaseapp.com',
    databaseURL: 'https://actingweb-firstapp.firebaseio.com',
    storageBucket: 'actingweb-firstapp.appspot.com',
    measurementId: 'G-M7F2YR6FNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7fSvAPIz-31x_pMPJ3hR3xMcP8WjJxJ0',
    appId: '1:748007732162:android:4684d6853ad93a3e',
    messagingSenderId: '748007732162',
    projectId: 'actingweb-firstapp',
    databaseURL: 'https://actingweb-firstapp.firebaseio.com',
    storageBucket: 'actingweb-firstapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFGeVdzEh6ZPKClV_0in0xHHX-0NtqGQ8',
    appId: '1:748007732162:ios:b662cf09a8209a8b785c5b',
    messagingSenderId: '748007732162',
    projectId: 'actingweb-firstapp',
    databaseURL: 'https://actingweb-firstapp.firebaseio.com',
    storageBucket: 'actingweb-firstapp.appspot.com',
    iosClientId: '748007732162-20hnc1u6qmn35avunaidj44p43o6g4s7.apps.googleusercontent.com',
    iosBundleId: 'io.actingweb.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFGeVdzEh6ZPKClV_0in0xHHX-0NtqGQ8',
    appId: '1:748007732162:ios:b662cf09a8209a8b785c5b',
    messagingSenderId: '748007732162',
    projectId: 'actingweb-firstapp',
    databaseURL: 'https://actingweb-firstapp.firebaseio.com',
    storageBucket: 'actingweb-firstapp.appspot.com',
    iosClientId: '748007732162-20hnc1u6qmn35avunaidj44p43o6g4s7.apps.googleusercontent.com',
    iosBundleId: 'io.actingweb.firstapp',
  );
}
